export { attest } from './attest.js'
export type { AttestTracer } from './attest.js'
export { sign, verify } from './signer.js'
export { createClient } from './client.js'
export type { AttestClient } from './client.js'
export { createBatcher } from './batcher.js'
export type { Batcher, BatcherDeps } from './batcher.js'
export type { AttestEvent, AttestOptions } from './types.js'
